nginx:
  image: manemonetech/warhol-nginx:latest
  ports:
    - '80:80'
  volumes_from:
    - datastore
  links:
    - rails

datastore:
  image: manemonetech/warhol-datastore:latest

rails:
  build: .
  env_file:
    - ./.env
  volumes_from:
    - datastore
