default: &pg_default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *pg_default
  database: warhol
  username: warhol
  password:
  host: localhost

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *pg_default
  database: <%= ENV['PRODUCTION_DATABASE_NAME'] %>
  username: <%= ENV['PRODUCTION_DATABASE_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
  host: <%= ENV['PRODUCTION_DATABASE_HOST'] %>
